version: "3.9"
services:
    miner:
        build: .
        container_name: pastel_walletnode
        command: >
                bash -c "./pastel-utility install walletnode --force || true
                && ./pastel-utility start walletnode
                && ps -A
                "